/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Asset */
        post: operations["create_asset_api_v1_assets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets/{asset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Asset */
        get: operations["get_asset_api_v1_assets__asset_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/listings/{listing_id}/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Prices */
        get: operations["list_prices_api_v1_listings__listing_id__prices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/market-data/issues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Market Data Issues */
        get: operations["list_market_data_issues_api_v1_market_data_issues_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/market-data/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Instruments */
        get: operations["search_instruments_api_v1_market_data_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Portfolio */
        post: operations["create_portfolio_api_v1_portfolios_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolios/{portfolio_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Portfolio */
        get: operations["get_portfolio_api_v1_portfolios__portfolio_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolios/{portfolio_id}/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Positions */
        get: operations["list_positions_api_v1_portfolios__portfolio_id__positions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolios/{portfolio_id}/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Snapshots */
        get: operations["list_snapshots_api_v1_portfolios__portfolio_id__snapshots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolios/{portfolio_id}/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Transactions */
        get: operations["list_transactions_api_v1_portfolios__portfolio_id__transactions_get"];
        put?: never;
        /** Execute Trade */
        post: operations["execute_trade_api_v1_portfolios__portfolio_id__transactions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolios/{portfolio_id}/transactions/{transaction_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Transaction */
        get: operations["get_transaction_api_v1_portfolios__portfolio_id__transactions__transaction_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness */
        get: operations["readiness_api_v1_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AssetCreate */
        AssetCreate: {
            asset_type: components["schemas"]["AssetType"];
            /** Currency */
            currency: string;
            /** Exchange Mic */
            exchange_mic: string;
            /** Exchange Timezone */
            exchange_timezone?: string | null;
            /** Isin */
            isin: string;
            /** Name */
            name: string;
            /** Provider Exchange Code */
            provider_exchange_code?: string | null;
            /** Provider Symbol */
            provider_symbol?: string | null;
            /** Sector */
            sector?: string | null;
            /** Ticker */
            ticker: string;
        };
        /** AssetResponse */
        AssetResponse: {
            asset_type: components["schemas"]["AssetType"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Currency */
            currency: string;
            /** Exchange Mic */
            exchange_mic: string;
            /** Exchange Timezone */
            exchange_timezone: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Isin */
            isin: string;
            /**
             * Listing Id
             * Format: uuid
             */
            listing_id: string;
            /** Name */
            name: string;
            /** Provider */
            provider: string;
            /** Provider Exchange Code */
            provider_exchange_code: string | null;
            /** Provider Symbol */
            provider_symbol: string | null;
            /** Sector */
            sector: string | null;
            /** Ticker */
            ticker: string;
        };
        /**
         * AssetType
         * @enum {string}
         */
        AssetType: "PUBLIC_EQUITY" | "UCITS_ETF";
        /** DataQualityIssueResponse */
        DataQualityIssueResponse: {
            /** Detail */
            detail: string;
            /**
             * Detected At
             * Format: date-time
             */
            detected_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Issue Type */
            issue_type: string;
            /** Listing Id */
            listing_id: string | null;
            /**
             * Observation Date
             * Format: date
             */
            observation_date: string;
            /** Resolved At */
            resolved_at: string | null;
            /** Status */
            status: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /** InstrumentMatchResponse */
        InstrumentMatchResponse: {
            /** Code */
            code: string;
            /** Country */
            country: string | null;
            /** Currency */
            currency: string | null;
            /** Exchange Code */
            exchange_code: string;
            /** Instrument Type */
            instrument_type: string;
            /** Is Primary */
            is_primary: boolean | null;
            /** Isin */
            isin: string | null;
            /** Name */
            name: string;
            /** Provider Symbol */
            provider_symbol: string;
        };
        /** PortfolioCreate */
        PortfolioCreate: {
            /**
             * Base Currency
             * @default EUR
             * @constant
             */
            base_currency: "EUR";
            /** Name */
            name: string;
            /**
             * Starting Capital
             * @default 10000.00
             */
            starting_capital: number | string;
        };
        /** PortfolioResponse */
        PortfolioResponse: {
            /** Base Currency */
            base_currency: string;
            /** Cash Balance */
            cash_balance: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Policy Version */
            policy_version: string;
            /** Realized Pnl */
            realized_pnl: string;
            /** Starting Capital */
            starting_capital: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version */
            version: number;
        };
        /** PortfolioSnapshotResponse */
        PortfolioSnapshotResponse: {
            /** Calculation Version */
            calculation_version: string;
            /** Cash Balance */
            cash_balance: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Input Fingerprint */
            input_fingerprint: string;
            /**
             * Portfolio Id
             * Format: uuid
             */
            portfolio_id: string;
            /** Positions */
            positions: components["schemas"]["SnapshotPositionResponse"][];
            /** Positions Value */
            positions_value: string;
            /** Realized Pnl */
            realized_pnl: string;
            /** Revision */
            revision: number;
            /** Supersedes Id */
            supersedes_id: string | null;
            /** Total Return */
            total_return: string;
            /** Total Value */
            total_value: string;
            /** Unrealized Pnl */
            unrealized_pnl: string;
            /**
             * Valuation Date
             * Format: date
             */
            valuation_date: string;
        };
        /** PositionResponse */
        PositionResponse: {
            /**
             * Asset Id
             * Format: uuid
             */
            asset_id: string;
            /** Average Cost */
            average_cost: string;
            /** Cost Basis */
            cost_basis: string;
            /**
             * Opened At
             * Format: date-time
             */
            opened_at: string;
            /**
             * Portfolio Id
             * Format: uuid
             */
            portfolio_id: string;
            /** Quantity */
            quantity: string;
            /** Realized Pnl */
            realized_pnl: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** PriceObservationResponse */
        PriceObservationResponse: {
            /** Adjusted Close */
            adjusted_close: string;
            /** Close */
            close: string;
            /** Currency */
            currency: string;
            /** High */
            high: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Listing Id
             * Format: uuid
             */
            listing_id: string;
            /** Low */
            low: string;
            /**
             * Observation Date
             * Format: date
             */
            observation_date: string;
            /** Open */
            open: string;
            /** Provider */
            provider: string;
            /** Provider Symbol */
            provider_symbol: string;
            /**
             * Retrieved At
             * Format: date-time
             */
            retrieved_at: string;
            /** Revision */
            revision: number;
            /** Source Checksum */
            source_checksum: string;
            /** Supersedes Id */
            supersedes_id: string | null;
            /** Volume */
            volume: string;
        };
        /** ReadinessResponse */
        ReadinessResponse: {
            /**
             * Status
             * @default ready
             * @constant
             */
            status: "ready";
        };
        /** SnapshotPositionResponse */
        SnapshotPositionResponse: {
            /**
             * Asset Id
             * Format: uuid
             */
            asset_id: string;
            /** Cost Basis */
            cost_basis: string;
            /** Fx Rate To Base */
            fx_rate_to_base: string;
            /**
             * Listing Id
             * Format: uuid
             */
            listing_id: string;
            /** Market Value */
            market_value: string;
            /** Price */
            price: string;
            /**
             * Price Date
             * Format: date
             */
            price_date: string;
            /** Quantity */
            quantity: string;
            /** Stale Days */
            stale_days: number;
            /** Unrealized Pnl */
            unrealized_pnl: string;
            /** Valuation Status */
            valuation_status: string;
        };
        /** TradeCreate */
        TradeCreate: {
            /**
             * Asset Id
             * Format: uuid
             */
            asset_id: string;
            /** Decision Id */
            decision_id?: string | null;
            /**
             * Executed At
             * Format: date-time
             */
            executed_at: string;
            /**
             * Fx Rate To Base
             * @default 1.000000000000
             */
            fx_rate_to_base: number | string;
            /** Quantity */
            quantity: number | string;
            /** Reference Price */
            reference_price: number | string;
            side: components["schemas"]["TradeSide"];
        };
        /** TradeResultResponse */
        TradeResultResponse: {
            /** Cash Balance */
            cash_balance: string;
            /** Portfolio Realized Pnl */
            portfolio_realized_pnl: string;
            position: components["schemas"]["PositionResponse"] | null;
            transaction: components["schemas"]["TransactionResponse"];
        };
        /**
         * TradeSide
         * @enum {string}
         */
        TradeSide: "BUY" | "SELL";
        /** TransactionResponse */
        TransactionResponse: {
            /** Asset Currency */
            asset_currency: string;
            /**
             * Asset Id
             * Format: uuid
             */
            asset_id: string;
            /** Cash Delta */
            cash_delta: string;
            /** Commission */
            commission: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Decision Id */
            decision_id: string | null;
            /**
             * Executed At
             * Format: date-time
             */
            executed_at: string;
            /** Execution Price */
            execution_price: string;
            /** Fx Fee */
            fx_fee: string;
            /** Fx Rate To Base */
            fx_rate_to_base: string;
            /** Gross Notional */
            gross_notional: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Portfolio Id
             * Format: uuid
             */
            portfolio_id: string;
            /** Quantity */
            quantity: string;
            /** Realized Pnl */
            realized_pnl: string;
            /** Reference Price */
            reference_price: string;
            side: components["schemas"]["TradeSide"];
            /** Slippage Cost */
            slippage_cost: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_asset_api_v1_assets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssetCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_asset_api_v1_assets__asset_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_prices_api_v1_listings__listing_id__prices_get: {
        parameters: {
            query: {
                date_from: string;
                date_to: string;
            };
            header?: never;
            path: {
                listing_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceObservationResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_market_data_issues_api_v1_market_data_issues_get: {
        parameters: {
            query?: {
                issue_status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataQualityIssueResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_instruments_api_v1_market_data_search_get: {
        parameters: {
            query: {
                q: string;
                exchange?: string | null;
                instrument_type?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstrumentMatchResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_portfolio_api_v1_portfolios_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortfolioCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_portfolio_api_v1_portfolios__portfolio_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_positions_api_v1_portfolios__portfolio_id__positions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_snapshots_api_v1_portfolios__portfolio_id__snapshots_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioSnapshotResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_transactions_api_v1_portfolios__portfolio_id__transactions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    execute_trade_api_v1_portfolios__portfolio_id__transactions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TradeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradeResultResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_transaction_api_v1_portfolios__portfolio_id__transactions__transaction_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: string;
                transaction_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readiness_api_v1_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
}
